### ISSUE TITLE
新版本只要下载batch_ro_cdk.py及gift_key.py就行了吗

### ISSUE THREAD

**Issue by Dlian-Zero** [shan333chao/xdro_batch_cdk#1]
作者您好，今天突然发现脚本更新了，多了很多文件，根据描述概况，是否只要batch_ro_cdk.py和gift_key.py就可以了？

**Comment by Dlian-Zero** [comment]
GAFT_CODE能否用list，多个礼包码兑换，踩楼活动会有4-5个礼包码
![image](https://github.com/shan333chao/xdro_batch_cdk/assets/52018129/b83d963a-5905-4f5c-bd11-5383a843710a)

**Comment by shan333chao** [comment]
> 作者您好，今天突然发现脚本更新了，多了很多文件，根据描述概况，是否只要batch_ro_cdk.py和gift_key.py就可以了？

是的 只要这俩就可以了  五区用不了  垃圾心动
